### PR TITLE
Create deploy script for DAO dashboard

### PR DESCRIPTION
**Pull request by Siegrift**

### CODE REVIEW

**Comment by Siegrift** [comment]
@bbenligiray @BritikovKI Can you review?

**Comment by bbenligiray** [comment]
Looks good to me but I'll let @BritikovKI take a look as well

**Review by BritikovKI — APPROVED** [review]
Seems like a good improvements

**Comment by BritikovKI** [comment]
Scripts are working now, with new version of api3voting on the network

**Pull request merged**
